

export const emojisList = [
  { emoji: "😀", name: "Grinning Face", keywords: ["grinning", "smile", "happy", "face"] },
  { emoji: "😁", name: "Beaming Face With Smiling Eyes", keywords: ["beaming", "smile", "happy"] },
  { emoji: "😂", name: "Face With Tears of Joy", keywords: ["joy", "tears", "laugh", "lol"] },
  { emoji: "🤣", name: "Rolling on the Floor Laughing", keywords: ["rofl", "laugh", "funny"] },
  { emoji: "😃", name: "Grinning Face With Big Eyes", keywords: ["smile", "big", "happy"] },
  { emoji: "😄", name: "Grinning Face With Smiling Eyes", keywords: ["smile", "happy", "joy"] },
  { emoji: "😅", name: "Grinning Face With Sweat", keywords: ["sweat", "awkward", "nervous"] },
  { emoji: "😆", name: "Grinning Squinting Face", keywords: ["laugh", "funny", "haha"] },
  { emoji: "😉", name: "Winking Face", keywords: ["wink", "flirt", "smile"] },
  { emoji: "😊", name: "Smiling Face With Smiling Eyes", keywords: ["smile", "happy", "warm"] },
  { emoji: "😇", name: "Smiling Face With Halo", keywords: ["angel", "innocent", "good"] },
  { emoji: "🙂", name: "Slightly Smiling Face", keywords: ["smile", "soft"] },
  { emoji: "🙃", name: "Upside-Down Face", keywords: ["upside", "sarcasm"] },
  { emoji: "☺️", name: "Smiling Face", keywords: ["smile", "warm"] },
  { emoji: "😋", name: "Face Savoring Food", keywords: ["yummy", "food", "delicious"] },
  { emoji: "😌", name: "Relieved Face", keywords: ["relieved", "calm"] },
  { emoji: "😍", name: "Smiling Face With Heart-Eyes", keywords: ["love", "heart", "like"] },
  { emoji: "🥰", name: "Smiling Face With Hearts", keywords: ["heart", "love", "happy"] },
  { emoji: "😘", name: "Face Blowing a Kiss", keywords: ["kiss", "love", "flirt"] },
  { emoji: "😗", name: "Kissing Face", keywords: ["kiss"] },
  { emoji: "😙", name: "Kissing Face With Smiling Eyes", keywords: ["kiss", "smile"] },
  { emoji: "😚", name: "Kissing Face With Closed Eyes", keywords: ["kiss", "closed"] },
  { emoji: "😜", name: "Winking Face With Tongue", keywords: ["wink", "tongue", "funny"] },
  { emoji: "😝", name: "Squinting Face With Tongue", keywords: ["tongue", "funny"] },
  { emoji: "😛", name: "Face With Tongue", keywords: ["tongue", "playful"] },
  { emoji: "🤑", name: "Money-Mouth Face", keywords: ["money", "rich"] },
  { emoji: "🤗", name: "Hugging Face", keywords: ["hug", "warm"] },
  { emoji: "🤭", name: "Face With Hand Over Mouth", keywords: ["oops", "shock"] },
  { emoji: "🫢", name: "Face With Open Eyes and Hand Over Mouth", keywords: ["shock", "surprise"] },
  { emoji: "🤫", name: "Shushing Face", keywords: ["quiet", "shh"] },
  { emoji: "🤔", name: "Thinking Face", keywords: ["think", "question"] },
  { emoji: "🤨", name: "Face With Raised Eyebrow", keywords: ["suspicious", "doubt"] },
  { emoji: "😐", name: "Neutral Face", keywords: ["neutral", "blank"] },
  { emoji: "😑", name: "Expressionless Face", keywords: ["expressionless", "blank"] },
  { emoji: "😶", name: "Face Without Mouth", keywords: ["silent", "mute"] },
  { emoji: "🫥", name: "Dotted Line Face", keywords: ["invisible", "fade"] },
  { emoji: "😶‍🌫️", name: "Face in Clouds", keywords: ["foggy", "lost", "confused"] },
  { emoji: "😏", name: "Smirking Face", keywords: ["smirk", "flirt"] },
  { emoji: "😒", name: "Unamused Face", keywords: ["unamused", "annoyed"] },
  { emoji: "🙄", name: "Face With Rolling Eyes", keywords: ["eyeroll", "bored"] },
  { emoji: "😬", name: "Grimacing Face", keywords: ["grimace", "awkward"] },
  { emoji: "😮‍💨", name: "Face Exhaling", keywords: ["exhale", "tired"] },
  { emoji: "🤥", name: "Lying Face", keywords: ["lie", "nose"] },
  { emoji: "😌", name: "Relieved Face", keywords: ["relief", "calm"] },
  { emoji: "😔", name: "Pensive Face", keywords: ["sad", "pensive"] },
  { emoji: "😪", name: "Sleepy Face", keywords: ["sleepy", "tired"] },
  { emoji: "🤤", name: "Drooling Face", keywords: ["drool"] },
  { emoji: "😴", name: "Sleeping Face", keywords: ["sleep", "zzz"] },
  { emoji: "🥱", name: "Yawning Face", keywords: ["yawn", "tired"] },
  { emoji: "😷", name: "Face With Medical Mask", keywords: ["mask", "sick"] },
  { emoji: "🤒", name: "Face With Thermometer", keywords: ["sick", "fever"] },
  { emoji: "🤕", name: "Face With Head-Bandage", keywords: ["injury", "hurt"] },
  { emoji: "🤢", name: "Nauseated Face", keywords: ["sick", "vomit"] },
  { emoji: "🤮", name: "Face Vomiting", keywords: ["vomit", "sick"] },
  { emoji: "🤧", name: "Sneezing Face", keywords: ["sneeze", "cold"] },
  { emoji: "🥵", name: "Hot Face", keywords: ["hot", "heat"] },
  { emoji: "🥶", name: "Cold Face", keywords: ["cold", "freeze"] },
  { emoji: "🥴", name: "Woozy Face", keywords: ["woozy", "drunk"] },
  { emoji: "😵", name: "Dizzy Face", keywords: ["dizzy"] },
  { emoji: "😵‍💫", name: "Face With Spiral Eyes", keywords: ["spiral", "confused"] },
  { emoji: "🤯", name: "Exploding Head", keywords: ["mindblown", "shock"] },
  { emoji: "🥳", name: "Partying Face", keywords: ["party", "celebration"] },
  { emoji: "😎", name: "Smiling Face With Sunglasses", keywords: ["cool", "swag"] },
  { emoji: "🤓", name: "Nerd Face", keywords: ["nerd", "geek"] },
  { emoji: "🧐", name: "Face With Monocle", keywords: ["monocle", "inspect"] },
  { emoji: "😕", name: "Confused Face", keywords: ["confused"] },
  { emoji: "😟", name: "Worried Face", keywords: ["worried"] },
  { emoji: "🙁", name: "Slightly Frowning Face", keywords: ["frown"] },
  { emoji: "☹️", name: "Frowning Face", keywords: ["frown", "sad"] },
  { emoji: "😮", name: "Face With Open Mouth", keywords: ["shock", "surprise"] },
  { emoji: "😯", name: "Hushed Face", keywords: ["hushed"] },
  { emoji: "😲", name: "Astonished Face", keywords: ["astonished", "shock"] },
  { emoji: "😳", name: "Flushed Face", keywords: ["flushed", "shy"] },
  { emoji: "🥺", name: "Pleading Face", keywords: ["please", "beg", "sad"] },
  { emoji: "😦", name: "Frowning Face With Open Mouth", keywords: ["frown", "shock"] },
  { emoji: "😧", name: "Anguished Face", keywords: ["anguish"] },
  { emoji: "😨", name: "Fearful Face", keywords: ["fear", "scared"] },
  { emoji: "😰", name: "Anxious Face With Sweat", keywords: ["anxious", "sweat"] },
  { emoji: "😥", name: "Sad but Relieved Face", keywords: ["sad", "relief"] },
  { emoji: "😢", name: "Crying Face", keywords: ["cry", "tear"] },
  { emoji: "😭", name: "Loudly Crying Face", keywords: ["cry", "tears", "sad"] },
  { emoji: "😱", name: "Face Screaming in Fear", keywords: ["scream", "fear"] },
  { emoji: "😖", name: "Confounded Face", keywords: ["confound"] },
  { emoji: "😣", name: "Persevering Face", keywords: ["persevere"] },
  { emoji: "😞", name: "Disappointed Face", keywords: ["disappointed"] },
  { emoji: "😓", name: "Downcast Face With Sweat", keywords: ["sweat", "sad"] },
  { emoji: "😩", name: "Weary Face", keywords: ["weary"] },
  { emoji: "😫", name: "Tired Face", keywords: ["tired"] },
  { emoji: "🥹", name: "Face Holding Back Tears", keywords: ["tears", "emotional"] },
  { emoji: "😤", name: "Face With Steam From Nose", keywords: ["angry", "steam"] },
  { emoji: "😡", name: "Pouting Face", keywords: ["angry", "pout"] },
  { emoji: "😠", name: "Angry Face", keywords: ["angry"] },
  { emoji: "🤬", name: "Face With Symbols on Mouth", keywords: ["censor", "angry"] },
  { emoji: "😈", name: "Smiling Face With Horns", keywords: ["devil", "horns", "evil"] },
  { emoji: "👿", name: "Angry Face With Horns", keywords: ["devil", "evil"] },
  { emoji: "💀", name: "Skull", keywords: ["skull"] },
  { emoji: "☠️", name: "Skull and Crossbones", keywords: ["danger", "poison"] },
  { emoji: "💩", name: "Pile of Poo", keywords: ["poo", "shit", "funny"] },
  { emoji: "🤡", name: "Clown Face", keywords: ["clown", "funny"] },
  { emoji: "👹", name: "Ogre", keywords: ["ogre", "monster"] },
  { emoji: "👺", name: "Goblin", keywords: ["goblin", "monster"] },
  { emoji: "👻", name: "Ghost", keywords: ["ghost", "spooky"] },
  { emoji: "👽", name: "Alien", keywords: ["alien"] },
  { emoji: "👾", name: "Alien Monster", keywords: ["monster", "alien"] },
  { emoji: "🤖", name: "Robot", keywords: ["robot"] },
  { emoji: "😺", name: "Grinning Cat", keywords: ["cat", "grin"] },
  { emoji: "😸", name: "Grinning Cat With Smiling Eyes", keywords: ["cat", "smile"] },
  { emoji: "😹", name: "Cat With Tears of Joy", keywords: ["cat", "cry", "joy"] },
  { emoji: "😻", name: "Smiling Cat With Heart-Eyes", keywords: ["cat", "love"] },
  { emoji: "😼", name: "Cat With Wry Smile", keywords: ["cat", "wry"] },
  { emoji: "😽", name: "Kissing Cat", keywords: ["cat", "kiss"] },
  { emoji: "🙀", name: "Weary Cat", keywords: ["cat", "weary"] },
  { emoji: "😿", name: "Crying Cat", keywords: ["cat", "cry"] },
  { emoji: "😾", name: "Pouting Cat", keywords: ["cat", "pout"] },
];